name             'masala_keepalived'
maintainer       'Joe Hohertz'
maintainer_email 'jhohertz@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures masala_keepalived'
long_description 'Installs/Configures masala_keepalived'
version          '0.1.0'

depends          'keepalived', '~> 1.3.0'
depends          'masala_base', '~> 0.1.0'
depends          'masala_ldap', '~> 0.1.0'
